import React from'react';import{NavLink,Navigate,Route,Routes}from'react-router-dom';import{CalendarDays,Home as HomeIcon,Users,Activity,BarChart3,MoreHorizontal}from'lucide-react';import{useTeamData}from'./lib/data.js';
const nav=[['/','Home',HomeIcon],['/calendario','Calendario',CalendarDays],['/rosa','Rosa',Users],['/partite','Partite',Activity],['/statistiche','Statistiche',BarChart3]];
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'—';const n=v=>Number(v||0);
function Mark({name='TM',url}){return <span className="mark">{url?<img src={url}/>:<b>{name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</b>}</span>}
function Shell({children}){return <><header className="top"><strong className="brand"><span className="shield">TM</span><span>TEAM MANAGER</span></strong><nav>{nav.map(([p,l,I])=><NavLink key={p} to={p}><I/>{l}</NavLink>)}</nav><button className="avatar">ES</button></header><main>{children}</main><nav className="bottom">{nav.slice(0,4).map(([p,l,I])=><NavLink key={p} to={p}><I/><span>{l}</span></NavLink>)}<NavLink to="/statistiche"><MoreHorizontal/><span>Altro</span></NavLink></nav></>}
function Home({d}){const now=Date.now(),past=d.matches.filter(x=>new Date(x.kickoff_at)<now||x.status==='finished').sort((a,b)=>new Date(b.kickoff_at)-new Date(a.kickoff_at)),future=d.matches.filter(x=>new Date(x.kickoff_at)>=now&&x.status!=='finished').sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)),last=past[0],next=future[0];const opp=id=>d.opponents.find(x=>x.id===id);const card=(m,title)=>{if(!m)return <section className="glass match hero"><small>{title}</small><h2>Nessuna partita</h2></section>;let o=opp(m.opponent_id),home=m.home_away==='home';return <section className="glass match hero"><small>{title} · {fmt(m.kickoff_at)}</small><div className="versus"><div><Mark name={home?'Calcio Caselle':o?.name} url={home?d.settings.team_logo_url:o?.logo_url}/><b>{home?'Calcio Caselle':o?.name}</b></div><strong>{m.status==='finished'?n(m.home_score)+' : '+n(m.away_score):'VS'}</strong><div><Mark name={home?o?.name:'Calcio Caselle'} url={home?o?.logo_url:d.settings.team_logo_url}/><b>{home?o?.name:'Calcio Caselle'}</b></div></div></section>};return <div className="page home"><div className="heroGrid">{card(last,'ULTIMO RISULTATO')}{card(next,'PROSSIMA PARTITA')}</div><div className="grid3"><Panel title="Ultimi risultati">{past.slice(0,5).map(m=><Result key={m.id} m={m} d={d}/>)}</Panel><Panel title="Classifica"><p className="muted">Classifica competizione collegata ai dati disponibili.</p></Panel><Panel title="Migliori marcatori">{[...d.stats].sort((a,b)=>n(b.goals)-n(a.goals)).slice(0,5).map((s,i)=><div className="row" key={s.player_id}><span>{i+1}. {d.players.find(p=>p.id===s.player_id)?.last_name||'—'}</span><b>{n(s.goals)}</b></div>)}</Panel></div></div>}
function Result({m,d}){let o=d.opponents.find(x=>x.id===m.opponent_id);return <div className="row"><span>{fmt(m.kickoff_at)} · {o?.name||'Avversario'}</span><b>{n(m.home_score)}–{n(m.away_score)}</b></div>}
function Panel({title,children}){return <section className="glass panel"><h3>{title}</h3>{children}</section>}
function Calendar({d}){return <div className="page"><Title t="Calendario" s="Programma completo della stagione"/><div className="calendarGrid">{d.matches.map(m=><section className="glass fixture" key={m.id}><time>{fmt(m.kickoff_at)}</time><Result m={m} d={d}/></section>)}</div></div>}
function Roster({d}){return <div className="page"><Title t="Rosa" s="Giocatori della squadra"/><div className="cards">{d.players.map(p=><section className="glass player" key={p.id}><span className="role">{p.generic_role_manual||'–'}</span><div><b>{p.first_name} {p.last_name}</b><small>{p.shirt_number?('#'+p.shirt_number):'Giocatore'}</small></div></section>)}</div></div>}
function Matches({d}){return <div className="page"><Title t="Partite" s="Live e gestione post-partita"/><Panel title="Partite">{d.matches.slice().reverse().map(m=><Result key={m.id} m={m} d={d}/>)}</Panel></div>}
function Stats({d}){const goals=[...d.stats].sort((a,b)=>n(b.goals)-n(a.goals));return <div className="page"><Title t="Statistiche" s="Prestazioni e classifiche"/><div className="statsGrid"><Ranking title="Classifica gol" rows={goals} d={d} field="goals"/><Ranking title="Classifica assist" rows={[...d.stats].sort((a,b)=>n(b.assists)-n(a.assists))} d={d} field="assists"/><Ranking title="Presenze e minutaggio" rows={[...d.stats].sort((a,b)=>n(b.appearances)-n(a.appearances))} d={d} field="appearances" extra="minutes_played"/><Ranking title="Ratings" rows={[...d.stats].sort((a,b)=>n(b.rating)-n(a.rating))} d={d} field="rating"/></div><Panel title="Distribuzione gol per fascia di minutaggio"><div className="minuteBands">{['0–15′','16–30′','31–45+′','46–60′','61–75′','76–90+′'].map(x=><span key={x}>{x}</span>)}</div></Panel></div>}
function Ranking({title,rows,d,field,extra}){return <Panel title={title}>{rows.slice(0,7).map((r,i)=><div className="row" key={r.player_id}><span>{i+1}. {d.players.find(p=>p.id===r.player_id)?.last_name||'—'}</span><b>{n(r[field])}{extra&&<small> · {n(r[extra])}′</small>}</b></div>)}</Panel>}
function Title({t,s}){return <div className="title"><h1>{t}</h1><p>{s}</p></div>}
export default function App(){const d=useTeamData();return <Shell>{d.loading?<div className="loader">TEAM MANAGER</div>:<Routes><Route path="/" element={<Home d={d}/>}/><Route path="/calendario" element={<Calendar d={d}/>}/><Route path="/rosa" element={<Roster d={d}/>}/><Route path="/partite" element={<Matches d={d}/>}/><Route path="/statistiche" element={<Stats d={d}/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}</Shell>}